## ASSIGNMENT

## EXERCISE A

In [15]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
import pingouin as pg
import scipy as sp
from scipy.stats import shapiro


gss = pd.read_csv("customerData.csv")
gss.head()

,customer_id,age,gender,income,monthly_spend,occupation,payment_type,city,education_level,satisfaction_score
0,1,56,Female,59148.54,24524.79,Business,Card,Nakuru,Masters,6
1,2,46,Female,45239.30,23544.97,Teacher,Bank Transfer,Mombasa,PhD,1
2,3,32,Female,71096.31,15464.20,Business,Mobile Money,Kisumu,Undergraduate,7
3,4,60,Female,52540.59,22059.59,Healthcare,Mobile Money,Nairobi,Masters,6
4,5,25,Male,63208.24,14784.25,IT,Bank Transfer,Kisumu,Masters,4

In [23]:
gss.dropna()

,customer_id,age,gender,income,monthly_spend,occupation,payment_type,city,education_level,satisfaction_score
0,1,56,Female,59148.54,24524.79,Business,Card,Nakuru,Masters,6
1,2,46,Female,45239.30,23544.97,Teacher,Bank Transfer,Mombasa,PhD,1
2,3,32,Female,71096.31,15464.20,Business,Mobile Money,Kisumu,Undergraduate,7
3,4,60,Female,52540.59,22059.59,Healthcare,Mobile Money,Nairobi,Masters,6
4,5,25,Male,63208.24,14784.25,IT,Bank Transfer,Kisumu,Masters,4
...,...,...,...,...,...,...,...,...,...,...
1195,1196,23,Female,57355.80,11580.24,Student,Card,Nairobi,Certificate,3
1196,1197,41,Female,71229.13,4739.74,Healthcare,Mobile Money,Mombasa,PhD,8
1197,1198,50,Female,69932.99,24624.42,IT,Card,Nairobi,Certificate,6
1198,1199,46,Female,67241.09,18943.55,Engineer,Mobile Money,Nairobi,Diploma,10
1199,1200,60,Female,53886.84,18037.27,Government,Mobile Money,Nairobi,PhD,5

## EXERCISE B One-Sample T-Test
### Choose a numeric variable (e.g., income, spend etc)
### Define a hypothesized population mean
### Perform a one-sample t-test and interpret the result

In [24]:
import pingouin as pg            

income_data = gss['income'].dropna()   

# Perform one-sample t-test against a population mean of 30
test_value = 50000
one_sample_test = pg.ttest(income_data, test_value)
one_sample_test

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,10.756726,1179,two-sided,8.300151e-26,"[53788.48, 55478.79]",0.31314,1.0,2.671e+22

In [25]:
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: sample mean is significantly different from the population mean.")
else:
    print("Fail to reject the null hypothesis: no significant difference between sample and population mean.")

Fail to reject the null hypothesis: no significant difference between sample and population mean.

## Exercise C: Two-Sample T-Test
### Split your data into two groups (e.g., male/female)
### Perform a two-sample t-test
### Report whether the difference is statistically significant

In [28]:
H0: the group means are significantly different.
H1: no significant difference between group means.
    
# Clean gender column
gss['gender'] = gss['gender'].str.strip().str.upper()

# Create groups
group_A = gss[gss['gender'] == 'MALE']['age'].dropna()
group_B = gss[gss['gender'] == 'FEMALE']['age'].dropna()

# Check sizes
print(len(group_A))
print(len(group_B))

# Perform t-test
import pingouin as pg

two_sample_test = pg.ttest(group_A, group_B, paired=False)

print(two_sample_test)

603
597
               T          dof alternative     p_val          CI95   cohen_d  \
T_test -0.306302  1190.884065   two-sided  0.759428  [-1.77, 1.3]  0.017691

           power   BF10
T_test  0.060806  0.068

In [34]:
group_A.head()

Series([], Name: age, dtype: int64)

In [35]:
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: the group means are significantly different.")
else:
    print("Fail to reject the null hypothesis: no significant difference between group means.")

Fail to reject the null hypothesis: no significant difference between group means.

## Exercise D: Chi-Square Test
### Select two categorical variables (e.g., occupation vs payment_type )
### Build a contingency table
### Perform a chi-square test for independence
### Interpret the result

In [40]:
import pandas as pd
from scipy import stats


contingency_table = pd.crosstab(gss["occupation"], gss["payment_type"])

# perform chi-square test
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

print("Chi-Square Test Result (Occupation vs Payment_type):")
print("Chi2:", chi2, "p-value:", p, "Degrees of Freedom:", dof)
print("p-value:", p)
print("Degrees of Freedom:", dof)

# Interpret the result
alpha = 0.05
if p < alpha:
    print("Reject the null hypothesis: there is a significant association between the variables.")
else:
    print("Fail to reject the null hypothesis: no significant association between the variables.")

Chi-Square Test Result (Occupation vs Payment_type):
Chi2: 13.341361433067203 p-value: 0.7709078218090677 Degrees of Freedom: 18
p-value: 0.7709078218090677
Degrees of Freedom: 18
Fail to reject the null hypothesis: no significant association between the variables.