# **Hypothesis Testing**
# **Brender - Data Analyst**

In [4]:
#!pip install pingouin

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy as sp
import pingouin as pg
import scipy.stats as stats
from scipy.stats import shapiro

## **Load the Dataset**

In [6]:
gss = pd.read_csv("GSSsubset.csv")
gss.head()

   id     sex       degree    income   marital   age  height  weight  hrswrk
0   1    MALE     BACHELOR  60967.50  DIVORCED  53.0    72.0   190.0    60.0
1   2  FEMALE     BACHELOR  60967.50   MARRIED  26.0    60.0    97.0    40.0
2   4  FEMALE     BACHELOR  10161.25   MARRIED  56.0    68.0   160.0    20.0
3  14  FEMALE  HIGH SCHOOL  17551.25   MARRIED  40.0    65.0   156.0    37.0
4  16    MALE  HIGH SCHOOL  17551.25   MARRIED  56.0     NaN   210.0     6.0

## **One Sample T-Test on Age**

In [7]:
age_data = gss['age'].dropna()

test_value = 30
one_sample_test = pg.ttest(age_data, test_value)
one_sample_test

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,34.722653,987,two-sided,2.884755e-173,"[43.68, 45.32]",1.104675,1.0,1.847e+169

## **One Sample T-Test on Income**

In [9]:
income_data = gss['income'].dropna()

test_value = 25000
one_sample_test = pg.ttest(income_data, test_value)
one_sample_test

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,10.7998,993,two-sided,8.752187e-26,"[34727.28, 39047.16]",0.342549,1.0,2.71e+22

## **One Sample T-Test on Height**

In [13]:
height_data = gss['height'].dropna()

test_value = 40
one_sample_test = pg.ttest(height_data, test_value)
one_sample_test

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,212.766313,983,two-sided,0.0,"[67.17, 67.68]",6.782742,1.0,inf

## **Two Sample T-Test**
### A two-sample t-test compares the means of two independent groups to determine if they differ significantly, assuming normal distribution and similar variances.

### a).Independent Two-Sample t-Test(Age by Gender)

In [21]:
#H0:There is no significant difference between average age across gender.
#H1:There is significant difference between average age across gender.

group_A = gss[gss['sex'] == 'MALE']['age'].dropna()
group_B = gss[gss['sex'] == 'FEMALE']['age'].dropna()

two_sample_test = pg.ttest(group_A,group_B, paired=False)
two_sample_test

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,1.015542,982.821172,two-sided,0.310098,"[-0.79, 2.49]",0.064651,0.173761,0.118

### b).Independent Two-Sample t-Test(Gender by Income)

In [22]:
#H0:There is no significant difference between average income across gender.
#H1:There is significant difference between average income across gender.

group_A = gss[gss['sex'] == 'MALE']['income'].dropna()
group_B = gss[gss['sex'] == 'FEMALE']['income'].dropna()

two_sample_test = pg.ttest(group_A,group_B, paired=False)
two_sample_test

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,8.950355,825.422137,two-sided,2.304728e-18,"[14673.48, 22917.25]",0.562372,1.0,2.429e+15

In [23]:
#H0:There is no significant difference between average hrswrk across gender.
#H1:There is significant difference between average hrswrk across gender.

group_A = gss[gss['sex'] == 'MALE']['hrswrk'].dropna()
group_B = gss[gss['sex'] == 'FEMALE']['hrswrk'].dropna()

two_sample_test = pg.ttest(group_A,group_B, paired=False)
two_sample_test

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,7.287648,975.993552,two-sided,6.503273e-13,"[4.76, 8.27]",0.464337,1.0,8.795e+09

####  Since P-Value < 0.05, we reject H0 and conclude that there is significant difference between average hrswrk across gender.

## **Paired t-Test**
### A paired sample t-test compares the means of two related groups(eg..,before-and-after measurements on the same subjects) to determine if the average difference between paired observations is statistically significant.

In [24]:
#H0:There is no significant difference on average test grades.
#H1:There is significant difference on average test grades.

before = [72,75,78,71,69,74,77,73,76,70]
after = [75,78,80,74,72,77,79,75,78,73]


# perform paired t-test
t_statistic, p_value = stats.ttest_rel(before, after)

# Output results
print("t-statistic:", t_statistic)
print("p-value:", p_value)

alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: there is no significant difference on average test grades.")

t-statistic: -15.921683328090657
p-value: 6.713856195677205e-08
Reject the null hypothesis: there is no significant difference on average test grades.

## Alternative

In [25]:
pg.ttest(before, after, paired = True)

,T,dof,alternative,p_val,CI95,cohen_d,power,BF10
T_test,-15.921683,9,two-sided,6.713856e-08,"[-2.97, -2.23]",0.908575,0.725205,1.65e+05

## Chi-Square Test for Independence

In [26]:
#H0:The two variables are independent (no relationship exists)
#H1:The two variables are dependent (there is a significant relationship)

contingency_table = pd.crosstab(gss["sex"],gss["marital"])

chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

print("Chi-Square Test Result(Gender vs Marital Status):")
print("Chi2:", chi2, "p-value:",p,"Degrees of Freedom:", dof)
print("p-value:", p)
print("Degree of Freedom:", dof)

alpha = 0.05
if p< alpha:
    print("Reject the null hypothesis: there is a significant association between the variables.")
else:
    print("Fail to reject the null hypothesis: no significant association between the variables.")

Chi-Square Test Result(Gender vs Marital Status):
Chi2: 6.211308199614711 p-value: 0.18391363117203863 Degrees of Freedom: 4
p-value: 0.18391363117203863
Degree of Freedom: 4
Fail to reject the null hypothesis: no significant association between the variables.

## Alternative 
## Indepence between sex and marital

In [31]:
import pingouin as pg

expected, observed, stats = pg.chi2_independence(data=gss, x='sex', y='marital')

In [32]:
expected

marital   DIVORCED     MARRIED  NEVER MARRIED  SEPARATED    WIDOWED
sex
FEMALE   84.269618  235.171026     131.793763  18.127767  17.637827
MALE     87.730382  244.828974     137.206237  18.872233  18.362173

In [33]:
observed

marital  DIVORCED  MARRIED  NEVER MARRIED  SEPARATED  WIDOWED
sex
FEMALE         85      220            140         19       23
MALE           87      260            129         18       13

In [34]:
stats

                 test    lambda      chi2  dof      pval    cramer     power
0             pearson  1.000000  6.211308  4.0  0.183914  0.079049  0.485258
1        cressie-read  0.666667  6.218386  4.0  0.183422  0.079094  0.485763
2      log-likelihood  0.000000  6.249637  4.0  0.181265  0.079293  0.487987
3       freeman-tukey -0.500000  6.288514  4.0  0.178613  0.079539  0.490748
4  mod-log-likelihood -1.000000  6.341226  4.0  0.175073  0.079872  0.494482
5              neyman -2.000000  6.491066  4.0  0.165354  0.080810  0.505024

## Independence between Marital and Degree

In [42]:
import warnings
warnings.filterwarnings('ignore')

In [43]:
#H0:The two variables are independent (no relationship exists)
#H1:The two variables are dependent (there is a significant relationship)

expected, observed, stats = pg.chi2_independence(data=gss, x='marital', y='degree')

In [37]:
expected

degree,BACHELOR,GRADUATE,HIGH SCHOOL,JUNIOR COLLEGE,LT HIGH SCHOOL
marital,,,,,
DIVORCED,36.164990,21.629779,84.961771,15.919517,13.323944
MARRIED,100.925553,60.362173,237.102616,44.426559,37.183099
NEVER MARRIED,56.560362,33.827968,132.876258,24.897384,20.838028
SEPARATED,7.779678,4.652918,18.276660,3.424547,2.866197
WIDOWED,7.569416,4.527163,17.782696,3.331992,2.788732

In [38]:
observed

degree         BACHELOR  GRADUATE  HIGH SCHOOL  JUNIOR COLLEGE  LT HIGH SCHOOL
marital
DIVORCED             28        19           93              19              13
MARRIED             122        75          203              41              39
NEVER MARRIED        52        25          151              26              15
SEPARATED             1         5           20               5               6
WIDOWED               6         1           24               1               4

In [39]:
stats

,test,lambda,chi2,dof,pval,cramer,power
0,pearson,1.000000,41.217044,16.0,5.157533e-04,0.101816,0.460371
1,cressie-read,0.666667,42.212360,16.0,3.668219e-04,0.103038,0.471997
2,log-likelihood,0.000000,45.648469,16.0,1.103228e-04,0.107149,0.511580
3,freeman-tukey,-0.500000,50.198234,16.0,2.131593e-05,0.112362,0.562271
4,mod-log-likelihood,-1.000000,57.708074,16.0,1.267233e-06,0.120474,0.640252
5,neyman,-2.000000,93.092863,16.0,6.712135e-13,0.153015,0.886296